source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘10.0’
install! 'cocoapods', generate_multiple_pod_projects: true
inhibit_all_warnings!    # 这个除去第三方库的警告
use_frameworks!          # 使用frameworks的方式
target 'JianZhiApp' do
    # Third Pay
    pod 'AFNetworking','~> 4.0'
    pod 'SDWebImage','~> 5.0'
    pod 'MBProgressHUD','~> 1.0' # 此框架有一个bug，所以修改了源码，设置defaultMotionEffectsEnabled为NO
    pod 'Masonry','~> 1.0'
    pod 'IQKeyboardManager','~> 6.0' 
    pod 'DZNEmptyDataSet','~> 1.0'
    pod 'TZImagePickerController','~> 3.0'
    pod 'ReactiveObjC','~> 3.0' # 目前是 3.1.1
    pod 'FFPopup','~> 1.0'
    pod 'JXCategoryView','~> 1.5' #分类切换滚动视图
    pod 'PromiseKit', '~> 6.0'
    pod 'CTMediator'
    pod 'IGListKit', '~> 4.0.0'
    # YY系列
    pod 'YYModel','~> 1.0'
    pod 'YYCache','~> 1.0'
    pod 'YYText','~> 1.0'
    pod 'KafkaRefresh','~> 1.0'
    pod 'TYCyclePagerView','~> 1.0'
    pod 'HWPanModal', '~> 0.6.0'
    #pod 'DGActivityIndicatorView','~> 2.0' # Loading 
    #pod 'JXCategoryView','1.5.2' #分类切换滚动视图
    #pod 'PromiseKit', '6.11.0' # 6.11.0 (was 6.9.0)
    #pod 'WebViewJavascriptBridge', '~> 6.0'
    #pod 'MLeaksFinder','1.0.0'
    #pod 'SDCycleScrollView','1.80' # 这个框架没有适配 generate_multiple_pod_projects ，手动修改#import <...>
    #pod 'MJRefresh','3.2.0'
    # SDK
    pod 'UMCCommon','2.1.4'
    pod 'UMCAnalytics','6.1.0'
     
end
